import { test,expect } from '@playwright/test';
import { makeGallery } from '../../src/devtools/scenarios';
import type { Page } from '@playwright/test';
async function panel(page:Page){await page.getByRole('button',{name:'Painel de teste',exact:true}).click()}
async function gallery(page:Page,kind:string){await panel(page);await page.getByLabel('Família de puzzle').selectOption(kind);await page.getByRole('button',{name:'Abrir galeria isolada'}).click();const preserve=page.getByRole('button',{name:'Preservar sessão e trocar'});if(await preserve.isVisible())await preserve.click()}
async function step(page:Page){await expect(page.locator('.reading-card,.options,.assembly,.blank-passage,.feedback,.result-main').first()).toBeVisible();if(page.url().endsWith('/result'))return;const reading=page.getByRole('button',{name:'Vamos praticar'}),cont=page.getByRole('button',{name:'Continuar',exact:true}),verify=page.getByRole('button',{name:'Verificar',exact:true});if(await reading.isVisible())await reading.click();else if(await cont.isVisible())await cont.click();else if(await verify.isVisible()){const options=page.getByRole('group',{name:'Alternativas'}).getByRole('button');if(await options.count())await options.first().click();else{const bank=page.getByLabel('Blocos disponíveis');while(await bank.locator('button:not([disabled])').count())await bank.locator('button:not([disabled])').first().click()}await verify.click()}else throw Error('Tela inesperada')}
test('primeira sessão, reload e resultado idempotente',async({page})=>{await page.goto('/explore');await expect(page.getByRole('heading',{name:'Escolha uma jornada.'})).toBeVisible();await expect(page.getByRole('button',{name:'Começar',exact:true})).toHaveCount(2);await page.getByRole('button',{name:'Começar',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Primeiro, uma leitura.'})).toBeVisible();await page.getByRole('button',{name:'Vamos praticar'}).click();const options=page.getByRole('group',{name:'Alternativas'}).getByRole('button');await expect(options).toHaveCount(4);const before=await options.allTextContents();await options.first().click();await page.reload();await expect(page.getByRole('button',{name:'Verificar'})).toBeEnabled();expect(await page.getByRole('group',{name:'Alternativas'}).getByRole('button').allTextContents()).toEqual(before);await page.getByRole('button',{name:'Verificar'}).click();await expect(page.getByRole('status')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Continuar',exact:true})).toBeVisible();for(let n=0;n<35&&!page.url().endsWith('/result');n++)await step(page);await expect(page.getByRole('heading',{name:'Prática concluída.'})).toBeVisible();const result=await page.locator('.result-summary').innerText();await page.reload();await expect(page.locator('.result-summary')).toHaveText(result,{useInnerText:true});await expect(page.getByRole('heading',{name:'Próximas revisões'})).toBeVisible()});
test('galeria: ordenação por teclado e pares com retomada',async({page})=>{await page.goto('/');await gallery(page,'order_fragments');const bank=page.getByLabel('Blocos disponíveis'),verify=page.getByRole('button',{name:'Verificar'});await expect(verify).toBeDisabled();await bank.getByRole('button').first().focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Passagem montada').getByRole('button',{name:/Remover bloco/})).toHaveCount(1);await page.getByLabel('Passagem montada').getByRole('button',{name:/Remover bloco/}).first().click();await expect(verify).toBeDisabled();while(await bank.locator('button:not([disabled])').count())await bank.locator('button:not([disabled])').first().click();await verify.click();await expect(page.getByRole('button',{name:'Continuar',exact:true})).toBeVisible();await gallery(page,'match_pairs');for(let n=0;n<3;n++){const left=page.getByLabel('Textos',{exact:true}).getByRole('button').filter({hasNot:page.locator('[disabled]')});const texts=page.locator('.pairs-grid>div:first-child button:not([disabled])');await texts.first().click();await page.locator('.pairs-grid>div:last-child button:not([disabled])').first().click();await expect(page.getByRole('status').last()).toBeVisible();await page.getByRole('button',{name:'Continuar',exact:true}).click();void left;}await expect(page.getByRole('heading',{name:'Prática concluída.'})).toBeVisible();await expect(page.locator('.result-summary')).toContainText('de 3')});
test('cenário de erro final, relógio isolado e exportação',async({page})=>{await page.goto('/');await panel(page);await page.getByLabel('Cenário',{exact:true}).selectOption('Erro no fim');await page.getByRole('button',{name:'Carregar cenário'}).click();await expect(page.getByRole('button',{name:'Continuar',exact:true})).toBeVisible();await page.getByRole('button',{name:'Continuar',exact:true}).click();await expect(page.getByRole('heading',{name:'Prática concluída.'})).toBeVisible();await panel(page);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar histórico JSON'}).click();expect((await download).suggestedFilename()).toContain('test');await page.getByRole('button',{name:'Voltar ao perfil real'}).click();await page.goto('/explore');await expect(page.getByRole('button',{name:'Começar',exact:true})).toHaveCount(2)});
test('telas responsivas, movimento reduzido e ausência de vazamento',async({page},info)=>{for(const width of [360,390,1440]){await page.setViewportSize({width,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/explore');await expect(page.getByRole('heading',{name:'Escolha uma jornada.'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`test-results/home-${info.project.name}-${width}.png`,fullPage:true});}await gallery(page,'locate_reference');await expect(page.locator('main .verse-reference')).toHaveCount(0);await expect(page.getByRole('button',{name:'Verificar'})).toBeDisabled();await page.setViewportSize({width:390,height:844});await page.screenshot({path:`test-results/puzzle-${info.project.name}-390.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)});
test('novas famílias: lacunas por toque e digitação normalizada',async({page})=>{
 await page.goto('/');await gallery(page,'fill_blanks');
 const verify=page.getByRole('button',{name:'Verificar'}),bank=page.getByLabel('Blocos disponíveis');
 await expect(verify).toBeDisabled();await bank.getByRole('button',{name:'amamos',exact:true}).click();await bank.getByRole('button',{name:'primeiro',exact:true}).click();await verify.click();await expect(page.locator('.feedback-heading')).toHaveText('Isso mesmo!');
 await gallery(page,'type_verse');await page.getByLabel('Escreva como você se lembra').fill('ALEGRAI VOS   SEMPRE');await verify.click();await expect(page.locator('.feedback-heading')).toHaveText('Isso mesmo!');
});
test('segunda jornada completa e zoom equivalente a 200%',async({page})=>{
 await page.setViewportSize({width:360,height:800});await page.goto('/explore');await page.getByRole('button',{name:'Começar',exact:true}).nth(1).click();
 for(let n=0;n<45&&!page.url().endsWith('/result');n++)await step(page);
 await expect(page.getByRole('heading',{name:'Prática concluída.'})).toBeVisible();
 // 720 CSS px at 200% becomes a 360 CSS px layout viewport.
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/result-360.png',fullPage:true});
});
test('pares parcialmente resolvidos sobrevivem ao reload do perfil de teste',async({page})=>{
 const fixture=makeGallery('match_pairs');fixture.mode='test';
 await page.goto('/');await page.evaluate(state=>{localStorage.setItem('gravatexto:test',JSON.stringify(state));sessionStorage.setItem('gravatexto:mode','test')},fixture);
 await page.goto('/session/gallery-session');
 const texts=page.locator('.pairs-grid>div:first-child button:not([disabled])');
 await texts.first().click();await page.locator('.pairs-grid>div:last-child button:not([disabled])').first().click();
 await expect(page.getByRole('button',{name:'Continuar',exact:true})).toBeVisible();
 await page.reload();await expect(page.getByRole('button',{name:'Continuar',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Continuar',exact:true}).click();await expect(texts).toHaveCount(2);
 const attempts=await page.evaluate(()=>JSON.parse(localStorage.getItem('gravatexto:test')!).attempts.length);expect(attempts).toBe(1);
});
test('home, trilha e navegação mobile apresentam progresso acessível',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await expect(page.getByRole('heading',{name:'Que bom ter você aqui.'})).toBeVisible();
 await expect(page.getByRole('navigation',{name:'Navegação principal'}).last()).toBeVisible();
 await page.getByRole('button',{name:'Ver trilha'}).click();
 await expect(page.getByRole('heading',{name:'Primeiros versículos'})).toBeVisible();
 await expect(page.getByRole('button',{name:/1 Tessalonicenses 5:16.*Disponível/})).toBeEnabled();
 await expect(page.getByRole('button',{name:/1 Tessalonicenses 5:17.*Bloqueado/})).toBeDisabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
