import { useLayoutEffect,useRef } from 'react';
import type { Instance } from '../../session/types';
import { Icon } from './Icon';
interface Props {i:Instance;select:(id:string)=>void;pair:(id:string)=>void;type:(value:string)=>void}
export function Puzzles({i,select,pair,type}:Props){
 if(['order_fragments','fill_blanks','initial_letters'].includes(i.kind))return <WordBank i={i} select={select}/>;
 if(i.kind==='type_verse')return <div className="typing-answer"><label htmlFor="typed-answer">Escreva como você se lembra</label><p className="hint">Acentos, maiúsculas e pontuação não entram na correção.</p><textarea id="typed-answer" value={i.selection[0]??''} onChange={e=>type(e.target.value)} disabled={!!i.feedback} maxLength={2000} autoComplete="off" autoCorrect="off" spellCheck={false} rows={5}/></div>;
 if(i.kind==='match_pairs'){const right=i.options.map(o=>i.pairs.find(p=>p.verse_id===o.id)!);
 return <><p className="hint">Toque em um texto e depois em sua referência.</p><div className="pairs-grid"><div aria-label="Textos"><h2>Textos</h2>{i.pairs.map(p=><button key={p.verse_id} className={`pair-piece ${i.pairSelected===p.verse_id?'selected':''} ${i.closed.includes(p.verse_id)?'resolved':''}`} disabled={!!i.feedback||i.closed.includes(p.verse_id)} aria-pressed={i.pairSelected===p.verse_id} onClick={()=>select(p.verse_id)}>{p.text}{i.closed.includes(p.verse_id)&&<Icon name="check" size={18}/>}</button>)}</div><div aria-label="Referências"><h2>Referências</h2>{right.map(p=><button key={p.verse_id} className={`pair-piece reference-piece ${i.closed.includes(p.verse_id)?'resolved':''}`} disabled={!!i.feedback||!i.pairSelected||i.closed.includes(p.verse_id)} onClick={()=>pair(p.verse_id)}>{p.reference}{i.closed.includes(p.verse_id)&&<Icon name="check" size={18}/>}</button>)}</div></div></>}
 return <div className="options" role="group" aria-label="Alternativas">{i.options.map((o,n)=><button className={`option ${i.selection.includes(o.id)?'selected':''}`} key={o.id} disabled={!!i.feedback} aria-pressed={i.selection.includes(o.id)} onClick={()=>select(o.id)}><span className="option-letter" aria-hidden="true">{String.fromCharCode(65+n)}</span><span>{o.label}</span>{i.selection.includes(o.id)&&<Icon name="check" size={19}/>}</button>)}</div>;
}

function WordBank({i,select}:{i:Instance;select:(id:string)=>void}){
 const root=useRef<HTMLDivElement>(null),positions=useRef(new Map<string,DOMRect>());
 useLayoutEffect(()=>{const next=new Map<string,DOMRect>();root.current?.querySelectorAll<HTMLElement>('[data-piece]').forEach(el=>{const id=el.dataset.piece!,rect=el.getBoundingClientRect(),old=positions.current.get(id);next.set(id,rect);if(old&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const x=old.left-rect.left,y=old.top-rect.top;if(x||y)el.animate([{transform:`translate(${x}px,${y}px)`},{transform:'translate(0,0)'}],{duration:190,easing:'cubic-bezier(.2,.7,.2,1)'})}});positions.current=next},[i.selection]);
 const selected=(n:number)=>i.pieces.find(p=>p.id===i.selection[n]);
 const slot=(n:number)=><button key={n} className={selected(n)?'piece placed':'empty-slot'} data-piece={selected(n)?.id} disabled={!!i.feedback||!selected(n)} onClick={()=>select(i.selection[n])} aria-label={selected(n)?`Remover bloco ${n+1}: ${selected(n)!.display_label}`:`Lacuna ${n+1}`}>{selected(n)?.display_label??`${n+1}`}{selected(n)&&<Icon name="close" size={14}/>}</button>;
 return <div ref={root}>{i.kind==='initial_letters'&&<p className="initial-hint" aria-label="Pista de iniciais">{i.hint}</p>}<div className={i.kind==='fill_blanks'?'blank-passage':'assembly'} aria-label="Passagem montada">{i.kind==='fill_blanks'?i.segments.map((segment,n)=><span key={n}>{segment}{n<i.correctOrder.length&&slot(n)}</span>):Array.from({length:i.correctOrder.length},(_,n)=>slot(n))}</div><p className="bank-label">Escolha {i.correctOrder.length} {i.kind==='fill_blanks'?'palavras':'blocos'} na ordem certa{i.pieces.length>i.correctOrder.length?' · há opções extras':''}</p><div className="piece-bank" aria-label="Blocos disponíveis">{i.pieces.filter(p=>!i.selection.includes(p.id)).map(p=><button className="piece" data-piece={p.id} disabled={!!i.feedback||i.selection.length>=i.correctOrder.length} key={p.id} onClick={()=>select(p.id)}>{p.display_label}</button>)}</div><p className="hint">Toque em uma peça montada para devolvê-la.</p></div>;
}
