import { useNavigate } from 'react-router-dom';
import growth from '../../assets/illustrations/daily-growth.svg';
import { content } from '../../content/adapt';
import { civilDay } from '../../progress/calendar';
import { dueDate,introduced } from '../../session/create';
import { earnedXp,practiceStreak } from '../../journey/model';
import { useStore } from '../store';
import { AppShell } from '../components/AppShell';
import { Brand } from '../components/Brand';
import { Icon } from '../components/Icon';

export function Home(){const {state,start,send}=useStore(),navigate=useNavigate(),today=civilDay(new Date().toISOString(),state.profile.timezone,state.dayOffset),active=Object.values(state.sessions).find(s=>['active','paused'].includes(s.status));const due=content.journeys.flatMap(j=>j.verseIds).filter((v,n,a)=>a.indexOf(v)===n&&introduced(state,v)&&dueDate(state,v)<=today),fresh=content.journeys.flatMap(j=>j.verseIds).find(v=>!introduced(state,v)),journey=active?.journeyId??content.journeys.find(j=>fresh&&j.verseIds.includes(fresh))?.id??content.journeys[0].id;
 const launch=()=>{if(active){send({sessionId:active.id,type:'resume'});navigate(`/session/${active.id}`);return}const id=start(journey);navigate(`/session/${id}`)};
 return <AppShell><header className="mobile-brand"><Brand/></header><main id="main" className="today-page"><div className="today-greeting"><div><h1>Que bom ter você aqui.</h1><p>Um encontro curto com o texto, no seu ritmo.</p></div><div className="status-cluster"><span><Icon name="sun"/>{practiceStreak(state)} <small>dias</small></span><span><Icon name="spark"/>{earnedXp(state)} <small>XP</small></span></div></div><section className="daily-mission"><div className="mission-copy"><h2>Sua missão de hoje</h2><p>{active?'Há uma prática esperando por você.':due.length?`${due.length} ${due.length===1?'revisão pede':'revisões pedem'} atenção.`:fresh?'Um novo texto está pronto para ser conhecido.':'Suas revisões estão em dia.'}</p><ul><li><Icon name={due.length?'repeat':'check'}/><span><strong>{due.length?`${due.length} para revisar`:'Revisões em dia'}</strong><small>{due.length?'Começamos por elas.':'A próxima chega na data agendada.'}</small></span></li>{fresh&&<li><Icon name="leaf"/><span><strong>1 nova leitura</strong><small>{content.items[fresh].reference}</small></span></li>}</ul><button className="button" onClick={launch}>{active?'Retomar prática':due.length?'Começar revisões':fresh?'Conhecer próximo texto':'Praticar livremente'}<Icon name="arrow"/></button></div><img src={growth} alt=""/></section><section className="today-journey"><div><h2>Sua caminhada</h2><p>{content.journeys.find(j=>j.id===journey)?.title}</p></div><div className="journey-snapshot"><span>{content.journeys.find(j=>j.id===journey)!.verseIds.filter(v=>introduced(state,v)).length}<small>de 6 textos apresentados</small></span><button onClick={()=>navigate(`/journey/${journey}`)}>Ver trilha <Icon name="arrow"/></button></div></section><section className="recent-milestone"><Icon name="star"/><div><h2>{earnedXp(state)?'Constância em construção':'Seu primeiro marco está próximo'}</h2><p>{earnedXp(state)?`${earnedXp(state)} XP registram respostas corretas independentes. XP descreve prática, não domínio.`:'Conclua uma prática para iniciar seu histórico local.'}</p></div></section></main></AppShell>}
