import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { content } from '../../content/adapt';
import { introduced,dueDate } from '../../session/create';
import { civilDay } from '../../progress/calendar';
import { useStore } from '../store';
import { Icon } from '../components/Icon';
import { Attribution } from '../components/Attribution';
import { AppShell } from '../components/AppShell';

export function Journeys(){const {state,start,send}=useStore(),navigate=useNavigate(),[pending,setPending]=useState<string|null>(null),active=Object.values(state.sessions).find(s=>['active','paused'].includes(s.status)),today=civilDay(new Date().toISOString(),state.profile.timezone,state.dayOffset);
 const launch=(id:string)=>{if(active&&active.journeyId!==id){setPending(id);return}if(active){send({sessionId:active.id,type:'resume'});navigate(`/session/${active.id}`);return}const sid=start(id);navigate(`/session/${sid}`)};
 return <AppShell><main id="main" className="explore-page"><header className="explore-heading"><div><h1>Escolha uma jornada.</h1><p>Duas trilhas curtas, com ritmos e imagens próprias.</p></div><Icon name="compass" size={34}/></header><div className="explore-list">{content.journeys.map((j,n)=>{const count=j.verseIds.filter(v=>introduced(state,v)).length,due=j.verseIds.filter(v=>introduced(state,v)&&dueDate(state,v)<=today).length,isActive=active?.journeyId===j.id;return <article className={`explore-journey explore-${n}`} key={j.id}><div className="explore-art"><img src={`/illustrations/${n===0?'pages':'tree'}.svg`} alt=""/><span>{n===0?'Começar pequeno':'Caminhar com calma'}</span></div><div className="explore-copy"><div className="journey-meta"><span>6 textos · 2 unidades</span><span>{count} apresentados</span></div><h2>{j.title}</h2><p>{j.description}</p><div className="six-marks" aria-label={`${count} de 6 textos apresentados`}>{Array.from({length:6},(_,i)=><span key={i} className={i<count?'done':''}/>)}</div><div className="explore-actions"><button className="button" onClick={()=>launch(j.id)}>{isActive?'Retomar':due?'Revisar':count?'Continuar':'Começar'}<Icon name="arrow"/></button><button className="text-button" onClick={()=>navigate(`/journey/${j.id}`)}>Ver trilha</button></div></div></article>})}</div>{pending&&<section className="resume-choice" role="alert"><h2>Há uma prática em andamento.</h2><p>Retome-a ou arquive as tentativas antes de trocar de jornada.</p><div className="button-row"><button className="button" onClick={()=>navigate(`/session/${active!.id}`)}>Retomar</button><button className="button button-light" onClick={()=>{send({sessionId:active!.id,type:'archive'});const id=start(pending);navigate(`/session/${id}`)}}>Arquivar e começar</button><button className="text-button" onClick={()=>setPending(null)}>Cancelar</button></div></section>}<footer className="explore-footer"><Attribution/></footer></main></AppShell>}
