import { useEffect,useRef } from 'react';
import { Link,Navigate,useNavigate,useParams } from 'react-router-dom';
import { content } from '../../content/adapt';
import { useStore } from '../store';
import { Icon } from '../components/Icon';
import { Puzzles } from '../components/Puzzles';
import { ContextPanel } from '../components/ContextPanel';
import { compareText } from '../../evaluation/text';
import { evaluateAnswer } from '../../evaluation/evaluate';
const modeLabel={learning:'Conhecer e praticar',review:'Hora de rever',mixed:'Rever e descobrir',free:'Prática livre',gallery:'Galeria de puzzles'};
export function Session(){const {id=''}=useParams(),{state,send}=useStore(),navigate=useNavigate(),s=state.sessions[id],i=s?.instances[s.cursor],heading=useRef<HTMLHeadingElement>(null),feedback=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(s?.status==='active'&&!s.reading&&!i?.presented)send({sessionId:id,type:'present'})},[id,s?.cursor,s?.reading,s?.readDone.length,s?.status,i?.presented]); // present is idempotent across reload and StrictMode
 useEffect(()=>{if(i?.feedback)feedback.current?.focus();else heading.current?.focus()},[i?.instanceId,i?.feedback?.verseId,s?.reading]);
 useEffect(()=>{if(s?.status!=='active'||!i?.presented||s.reading||i.feedback)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now(),ms=now-last;last=now;if(document.visibilityState==='visible'&&document.hasFocus())send({sessionId:id,type:'tick',ms})},1000);return()=>clearInterval(timer)},[id,i?.instanceId,i?.presented,i?.feedback,s?.reading,s?.status]);
 if(!s)return <Missing/>;
 if(s.status==='completed')return <Navigate to={`/session/${id}/result`} replace/>;
 if(s.status==='archived')return <Missing message="Esta sessão foi arquivada. Suas tentativas continuam guardadas."/>;
 if(s.status==='paused')return <main className="simple-page"><Icon name="book" size={48}/><h1>Seu lugar está guardado.</h1><p>Continue exatamente de onde parou.</p><button className="button" onClick={()=>send({sessionId:id,type:'resume'})}>Retomar sessão<Icon name="arrow"/></button><Link to="/">Voltar às jornadas</Link></main>;
 if(!i||(!i.presented&&!s.reading))return <main className="simple-page"><p>Preparando sua prática…</p></main>;
 const reading=s.reading?content.items[s.reading]:null,reinforce=i.phase==='reinforcement',completedBase=Math.min(s.cursor,s.baseCount),totalReinforce=s.instances.length-s.baseCount,ready=evaluateAnswer(i,i.selection)!==null;
 const leave=()=>{send({sessionId:id,type:'pause'});navigate('/')};
 const recent=state.attempts.filter(a=>a.sessionId===id);let streak=0;for(const a of [...recent].reverse()){if(!a.correct||a.assisted)break;streak++}
 const diff=i.kind==='type_verse'&&i.feedback?compareText(i.expectedText,i.selection[0]??''):null;
 const fb=i.feedback?content.items[i.feedback.verseId]:null;
 return <div className="session-shell"><header className="session-header"><button className="icon-button" onClick={leave} aria-label="Sair e guardar sessão"><Icon name="close"/></button><div className="session-progress"><div className="progress-label"><span>{reinforce?'Vamos reforçar':modeLabel[s.mode]}</span><span>{reinforce?`${s.cursor-s.baseCount+1} de ${totalReinforce}`:`${completedBase} de ${s.baseCount}`}</span></div><div className="progress-track" role="progressbar" aria-label="Desafios-base concluídos" aria-valuenow={completedBase} aria-valuemin={0} aria-valuemax={s.baseCount}><span style={{transform:`scaleX(${completedBase/Math.max(1,s.baseCount)})`}}/></div></div><Icon name="book" size={26}/></header><main id="main" className={`session-body ${i.kind==='match_pairs'?'wide-puzzle':''}`}>
 {reading?<div className="reading-card"><div className="reading-icon"><Icon name="book" size={32}/></div><h1 ref={heading} tabIndex={-1}>Primeiro, uma leitura.</h1><p className="reading-intro">Leia com calma. Depois, vamos praticar.</p><blockquote>{reading.text}</blockquote><p className="verse-reference">{reading.reference}</p><div className="editorial-note"><h2>Um pouco de contexto</h2><p>{reading.context_note}</p><ContextPanel key={reading.id} verseId={reading.verse_id} sessionId={id}/></div><p className="source-label">Bíblia Livre · Textus Receptus · 2018.2.0</p></div>:<><h1 ref={heading} tabIndex={-1} className="puzzle-title">{i.prompt}</h1>{i.kind!=='locate_reference'&&i.kind!=='match_pairs'&&<p className="verse-reference">{i.reference}</p>}{i.kind==='locate_reference'&&<blockquote className="puzzle-verse">{i.text}</blockquote>}{i.kind==='fill_gap'&&<blockquote className="puzzle-verse">{i.prefix}<span className="gap" aria-label="lacuna">{i.feedback?i.options.find(o=>o.id===i.correct)?.label:'•••'}</span>{i.suffix}</blockquote>}{i.kind==='choose_continuation'&&<blockquote className="puzzle-verse">{i.prefix}<span className="continuation-mark">…</span></blockquote>}<Puzzles i={i} type={value=>send({sessionId:id,type:'type',value})} select={value=>send({sessionId:id,type:'select',value})} pair={value=>send({sessionId:id,type:'pair',value})}/>{!i.feedback&&<p className={["order_fragments","fill_blanks","initial_letters"].includes(i.kind)?"sr-only":"puzzle-footnote"}>{['order_fragments','fill_blanks','initial_letters'].includes(i.kind)?`${i.selection.length} de ${i.correctOrder.length} peças montadas`:i.kind==='type_verse'?'Digite sua resposta e verifique quando estiver pronto.':i.kind==='match_pairs'?`${i.closed.length} de 3 associações concluídas`:'Escolha uma opção. Você pode mudar antes de verificar.'}</p>}</>}
 </main><footer className={`session-footer ${i.feedback?(i.feedback.correct?'correct-feedback':'incorrect-feedback'):''}`}><div className="footer-inner">{i.feedback&&fb&&<div className="feedback" ref={feedback} tabIndex={-1} role="status"><div className="feedback-heading"><Icon name={i.feedback.correct?'check':'info'} size={25}/><h2>{i.feedback.correct?'Isso mesmo!':'Vamos guardar esta associação.'}</h2></div><p>{fb.text}</p><strong>{fb.reference}</strong>{diff&&!diff.correct&&<div className="text-diff">{diff.missing.length>0&&<p><b>Palavras a lembrar:</b> {diff.missing.join(' · ')}</p>}{diff.extra.length>0&&<p><b>Palavras diferentes ou extras:</b> {diff.extra.join(' · ')}</p>}</div>}{i.feedback.correct&&streak>=3&&<p className="streak"><Icon name="leaf" size={18}/>{streak} respostas certas seguidas nesta prática</p>}{!i.feedback.correct&&<p className="feedback-help">Você vai reencontrar esta dificuldade em outra revisão.</p>}<ContextPanel key={i.instanceId+fb.id} verseId={fb.verse_id} sessionId={id}/></div>}{reading?<button className="button" onClick={()=>send({sessionId:id,type:'read'})}>Vamos praticar<Icon name="arrow"/></button>:i.feedback?<button className="button" onClick={()=>send({sessionId:id,type:'continue'})}>Continuar<Icon name="arrow"/></button>:i.kind==='match_pairs'?<p className="hint">{i.pairSelected?'Agora escolha uma referência.':'Comece escolhendo um texto.'}</p>:<button className="button" disabled={!ready} onClick={()=>send({sessionId:id,type:'verify'})}>Verificar<Icon name="check"/></button>}</div></footer></div>;
}
export function Missing({message='Não encontramos esta sessão neste navegador.'}:{message?:string}){return <main className="simple-page"><Icon name="book" size={44}/><h1>Vamos voltar às jornadas?</h1><p>{message}</p><Link className="button" to="/">Voltar às jornadas<Icon name="arrow"/></Link></main>}
