import { z } from 'zod';
import type { State } from '../session/types';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),at=z.iso.datetime(),str=z.string(),num=z.number().finite(),ids=z.array(str),dim=z.enum(['text','reference']);
const progress=z.object({introducedAt:at,lastPresented:z.union([at,z.literal('')]),due:date,step:z.number().int().min(0).max(4),evaluations:z.number().int().nonnegative()});
const instance=z.object({difficulty:num.default(1),segments:ids.default([]),hint:str.default(''),expectedText:str.default(''),id:str,kind:z.enum(['locate_reference','identify_text','fill_gap','choose_continuation','order_fragments','match_pairs','fill_blanks','initial_letters','type_verse']),dimension:dim,verseIds:ids.min(1).max(3),prompt:str,text:str,reference:str,prefix:str,suffix:str,options:z.array(z.object({id:str,label:str})),correct:str,pieces:z.array(z.object({id:str,text:str,display_label:str})),correctOrder:ids,pairs:z.array(z.object({verse_id:str,text:str,reference:str})),instanceId:str,phase:z.enum(['base','reinforcement']),selection:ids,pairSelected:str.nullable(),closed:ids,presented:z.boolean(),feedback:z.object({correct:z.boolean(),verseId:str}).nullable(),activeMs:num.nonnegative()});
const result=z.object({baseTotal:num,baseCorrect:num,assisted:num,reinforcementTotal:num,reinforcementCorrect:num,verseIds:ids,difficulties:z.array(z.object({verseId:str,dimension:dim})),reviews:z.array(z.object({verseId:str,dimension:dim,due:date}))});
const session=z.object({id:str,journeyId:str,originNodeId:str.optional(),contentVersion:str,seed:num,dayOffset:num.int(),createdAt:at,mode:z.enum(['learning','review','mixed','free','gallery']),activeVerseIds:ids.max(3),newVerseIds:ids.max(2),baseCount:num.int().min(0).max(8),instances:z.array(instance).max(11),cursor:num.int().nonnegative(),status:z.enum(['active','paused','archived','completed']),reading:str.nullable(),readDone:ids,exposures:z.array(z.object({verseId:str,dimension:dim,screen:num.int().nonnegative(),at,source:str})),queue:z.array(z.object({verseId:str,dimension:dim,order:num,isNew:z.boolean(),served:z.boolean()})),shortReason:str.nullable(),result:result.nullable()}).refine(s=>s.cursor<=s.instances.length&&s.baseCount<=s.instances.length&&(s.status!=='completed'||s.result!==null));
const schema=z.object({preferences:z.object({typingEnabled:z.boolean()}).default({typingEnabled:false}),milestones:ids.default([]),schema_version:z.literal(1),profile:z.object({id:str,timezone:str.refine(t=>{try{new Intl.DateTimeFormat('pt-BR',{timeZone:t});return true}catch{return false}})}),mode:z.enum(['normal','test','gallery']),dayOffset:num.int(),progress:z.record(str,progress),daily:z.record(str,z.object({before:progress,firstAttempt:str,failed:z.boolean(),advanced:z.boolean()})),sessions:z.record(str,session),attempts:z.array(z.object({id:str,sessionId:str,instanceId:str,verseId:str,dimension:dim,answer:ids,correct:z.boolean(),assisted:z.boolean(),exposed:z.boolean(),phase:z.enum(['base','reinforcement']),day:date,at,activeMs:num})),events:z.array(z.object({id:str,type:str,sessionId:str,at,day:date,instanceId:str.optional(),details:str.optional()}))}).passthrough();
export function migrateState(value:unknown):State {
 const s=schema.parse(value) as State;
 if(Object.values(s.sessions).filter(s=>['active','paused'].includes(s.status)).length>1)throw Error('Mais de uma sessão ativa');
 if(new Set(s.attempts.map(a=>a.id)).size!==s.attempts.length||new Set(s.events.map(a=>a.id)).size!==s.events.length)throw Error('Histórico duplicado');
 return s;
}
